SELECT
	AR.CODARTICULO AS id,
	CASE
		WHEN ST.CODALMACEN = '2' THEN '900174620'
		WHEN ST.CODALMACEN = '3' THEN '900175196'
		WHEN ST.CODALMACEN = '50' THEN '900175197'
		WHEN ST.CODALMACEN = '1' THEN '900175315'
		ELSE '0'
	END AS store_id,
	REPLACE(REPLACE(AR.REFPROVEEDOR, CHAR(10), ''), CHAR(13), '') AS ean,
	AR.DESCRIPCION AS name,
	M.DESCRIPCION AS trademark,
	AR.DESCRIPCION AS description,
	COALESCE((PV.PNETO + AR.CARGO1), 0) AS price,
	0 AS discount_price,
	ST.STOCK AS stock,
	CASE
		WHEN AR.UNIDADMEDIDA = 'Un' THEN 'U'
		WHEN AR.UNIDADMEDIDA = 'Kg' THEN 'WW'
		ELSE 'U'
	END AS sale_type,
	CASE
		WHEN ST.STOCK <= 0 THEN 'FALSE'
		WHEN ST.STOCK > 0 THEN 'TRUE'
		ELSE 'FALSE'
	END AS is_available,
	D.DESCRIPCION AS Departamento,
	S.DESCRIPCION AS secciones,
	F.DESCRIPCION AS Familia,
	SF.DESCRIPCION AS SubFamilia,
	CONCAT(AR.CODARTICULO, 
    CASE 
        WHEN ST.CODALMACEN = '2' THEN '900174620' 
        WHEN ST.CODALMACEN = '3' THEN '900175196'
        WHEN ST.CODALMACEN = '50' THEN '900175197'
        WHEN ST.CODALMACEN = '1' THEN '900175315'
        ELSE '0'
    END) AS Code
FROM
	STOCKS ST
INNER JOIN ARTICULOS AR ON ST.CODARTICULO = AR.CODARTICULO
INNER JOIN PRECIOSVENTA PV ON AR.CODARTICULO = PV.CODARTICULO
LEFT JOIN ARTICULOSCAMPOSLIBRES ACL ON AR.CODARTICULO = ACL.CODARTICULO
LEFT JOIN MARCA M ON AR.MARCA = M.CODMARCA
LEFT JOIN DEPARTAMENTO D ON AR.DPTO = D.NUMDPTO
LEFT JOIN SECCIONES S ON AR.DPTO = S.NUMDPTO AND AR.SECCION = S.NUMSECCION
LEFT JOIN FAMILIAS F ON AR.DPTO = F.NUMDPTO AND AR.SECCION = F.NUMSECCION AND AR.FAMILIA = F.NUMFAMILIA
LEFT JOIN SUBFAMILIAS SF ON AR.DPTO = SF.NUMDPTO AND AR.SECCION = SF.NUMSECCION AND AR.FAMILIA = SF.NUMFAMILIA AND AR.SUBFAMILIA = SF.NUMSUBFAMILIA
WHERE
	AR.DESCATALOGADO = 'F'
	AND ST.CODALMACEN IN ('1', '3', '50', '2')
	AND PV.IDTARIFAV = 1
UNION
SELECT
	AR.CODARTICULO AS id,
	CASE
		WHEN ST.CODALMACEN = '2' THEN '900174620'
		WHEN ST.CODALMACEN = '3' THEN '900175196'
		WHEN ST.CODALMACEN = '50' THEN '900175197'
		WHEN ST.CODALMACEN = '1' THEN '900175315'
		ELSE '0'
	END AS store_id,
	-- Remover saltos de línea del código de barras (ean)
	REPLACE(REPLACE(AR.REFPROVEEDOR, CHAR(10), ''), CHAR(13), '') AS ean,
	AR.DESCRIPCION AS name,
	M.DESCRIPCION AS trademark,
	AR.DESCRIPCION AS description,
	-- Asegurar que price nunca sea NULL, asignando 0 como valor predeterminado
	COALESCE((PV.PNETO + AR.CARGO1), 0) AS price,
	0 AS discount_price,
	ST.STOCK AS stock,
	CASE
		WHEN AR.UNIDADMEDIDA = 'Un' THEN 'U'
		WHEN AR.UNIDADMEDIDA = 'Kg' THEN 'WW'
		ELSE 'U'
	END AS sale_type,
	CASE
		WHEN ST.STOCK <= 0 THEN 'FALSE'
		WHEN ST.STOCK > 0 THEN 'TRUE'
		ELSE 'FALSE'
	END AS is_available,
	D.DESCRIPCION AS Departamento,
	S.DESCRIPCION AS secciones,
	F.DESCRIPCION AS Familia,
	SF.DESCRIPCION AS SubFamilia,
	CONCAT(AR.CODARTICULO, 
    CASE 
        WHEN ST.CODALMACEN = '2' THEN '900174620' 
        WHEN ST.CODALMACEN = '3' THEN '900175196'
        WHEN ST.CODALMACEN = '50' THEN '900175197'
        WHEN ST.CODALMACEN = '1' THEN '900175315'
        ELSE '0'
    END) AS Code
FROM
	STOCKS ST
INNER JOIN ARTICULOS AR ON ST.CODARTICULO = AR.CODARTICULO
INNER JOIN PRECIOSVENTA PV ON AR.CODARTICULO = PV.CODARTICULO
LEFT JOIN ARTICULOSCAMPOSLIBRES ACL ON AR.CODARTICULO = ACL.CODARTICULO
LEFT JOIN MARCA M ON AR.MARCA = M.CODMARCA
LEFT JOIN DEPARTAMENTO D ON AR.DPTO = D.NUMDPTO
LEFT JOIN SECCIONES S ON AR.DPTO = S.NUMDPTO AND AR.SECCION = S.NUMSECCION
LEFT JOIN FAMILIAS F ON AR.DPTO = F.NUMDPTO AND AR.SECCION = F.NUMSECCION AND AR.FAMILIA = F.NUMFAMILIA
LEFT JOIN SUBFAMILIAS SF ON AR.DPTO = SF.NUMDPTO AND AR.SECCION = SF.NUMSECCION AND AR.FAMILIA = SF.NUMFAMILIA AND AR.SUBFAMILIA = SF.NUMSUBFAMILIA
WHERE
	AR.DESCATALOGADO = 'F'
	AND ACL.ARTICULOTM = 'SI'
	AND ST.CODALMACEN IN ('1', '3', '50', '2')
	AND PV.IDTARIFAV = 1;